---
- name: Install required dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install Docker Engine and Docker Compose plugin
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Create project directory
  ansible.builtin.file:
    path: /opt/myapp
    state: directory
    mode: "0755"

- name: Copy Docker Compose files
  ansible.builtin.copy:
    src: files/
    dest: /opt/myapp
    mode: preserve

- name: Run docker-compose up
  community.docker.docker_compose_v2:
    project_src: /opt/myapp
    state: present
