---
- name: Install NGINX
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Set Nginx conf file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/sites-available/default"
    mode: "0755"
  notify: Reload nginx
