version: '3.8'
services:
  nginx:
    image: nginx:latest
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    build: ./app
    expose:
      - "8000"